# Docker image with all python environments
# https://github.com/themattrix/docker-tox
image: themattrix/tox
# image: python:3.5

py.test:
  only:
    - master
    - /^devel.*$/
  before_script:
    #- apt-get -y update
    #- apt-get install -y gfortran
    - python --version
    - pip install -U tox
    - tox --version
  script:
    - tox
