language: python
sudo: required
dist: trusty

services:
  - mongodb
  
matrix:
    include:
        #- python: 3.4
        #  env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libgeos-dev
install:
  - pip install -U pip
  - pip install -U tox
script: travis_wait 30 tox -e ${TOXENV}
